# fly.toml app configuration file generated for pet-my-pet on 2024-06-07T15:26:53+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pet-my-pet'
primary_region = 'ams'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:migrate'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
